### ISSUE TITLE
Là một học sinh, tôi có thể sử dụng bộ từ tiếng Anh có sẵn phong phú để dễ dàng học và ghi nhớ từ mới.

### ISSUE THREAD

**Issue by thienanh1999** [lightkuriboh/INT2208-8-2019#2]
### Đánh giá **INVEST**:
1. **Independent** : Việc truy xuất dữ liệu từ database có thể được tiến hành độc lập, không sử dụng chung tài nguyên và không gian dữ liệu với các user stories khác.
2. **Negotiable** : User story này đủ lớn và không quá chi tiết nên người thực hiện có thể linh hoạt trong quá trình thực hiện để phù hợp hơn với các công việc khác trong project.
3. **Valuable** : Sử dụng bộ dữ liệu có sẵn và chức năng học từ là tình năng chính của một ứng dụng học từ tiếng Anh
4. **Estimatable** : User story có độ lớn vừa đủ để có thể chia nhỏ thành các tasks, dễ dàng hơn trong việc quản lý và thực hiện
5. **Small** : User story không quá lớn, chỉ bao gồm 1 tính năng riêng biệt
6. **Testable** : Với các từ được truy xuất từ bộ dữ liệu, tester có thể dễ dàng kiểm thử tính đúng/sai và chất lượng của từ một cách trực quan.

### Task list:

- [x] Làm rõ yêu cầu (giao diện cần những gì, xác định bộ dữ liệu cần chuẩn bị, hình dung flow chương trình, ...)

- [x] Xây dựng user story dựa trên mô hình MVC
- Tài liệu tham khảo về mô hình MVC: https://www.tutorialspoint.com/mvc_framework/mvc_framework_introduction.htm

- [x] Chuẩn bị bộ dữ liệu từ vựng có sẵn (bao gồm từ, dịch nghĩa, hình ảnh minh hoạt, phát âm, ví dụ, dịch ví dụ,...)
- Update: Bộ dữ liệu gồm 600 từ chia theo các topic và category đã được chuẩn bị

- [x] Thiết kết UI bao gồm 2 màn hình:
- Màn hình chính : Hiển thị danh sách các category và các topic
- Màn hình học tập : Gồm các plascard biểu diễn 1 từ bất kì để học / review

- [x] Tìm hiểu về SQLite để quản lý bộ dữ liệu offline:
- SQLite là gì : https://www.tutorialspoint.com/sqlite/
- SQLite cho Android : https://www.tutorialspoint.com/android/android_sqlite_database.htm

- [x] Tìm hiểu về các UI component của Android:
- View Group: https://developer.android.com/reference/android/view/ViewGroup
- Expandable ListView: https://developer.android.com/reference/android/widget/ExpandableListView

- [x] Tìm hiểu về service, broadcast receiver: 
- Broadcast Receiver : https://developer.android.com/guide/components/broadcasts

- [x] Viết Util truy xuất data từ bộ dữ liệu có sẵn https://github.com/lightkuriboh/INT2208-8-2019/commit/45a52a2a911a730d61b9a5092fae6b243306d5d4

- [x] Thêm reminder service và screen service https://github.com/lightkuriboh/INT2208-8-2019/commit/a692f628700c349ec028f2df25e896cb9375b2c3

- [x] Thực hiện màn hình chính và màn hình học tập

- [x] Thêm tính năng hiển thị quá trình học tập qua progress bar và hiển thị lần cuối học

- [x] Kiểm thử
